### ISSUE TITLE
[Client] We received error 10057

### ISSUE THREAD

**Issue by hanlongppl** [RevenantX/LiteNetLib#184]
当ipad锁屏之后，再解锁，就不能跟服务器通讯了，一直输出”we received error 10057"

**Comment by RevenantX** [comment]
From msdn:
WSAENOTCONN 10057 | Socket is not connected.   A request to send or receive data was disallowed because the socket is  not connected and (when sending on a datagram socket using sendto) no address was supplied. Any other type of operation might also return  this error—for example, setsockopt setting SO_KEEPALIVE if the connection has been reset.

**Comment by RevenantX** [comment]
@hanlongppl so possibly you just somwhere passed empty IPEndPoint (or NetEndPoint in 0.7.x version)
