### ISSUE TITLE
ConnectId not always unique

### ISSUE THREAD

**Issue by Mukikaizoku** [RevenantX/LiteNetLib#231]
As mentioned in comment in #181, the generated ConnectId can possibly be the same for two connections that happen to connect about the same time. The potential duplication of ConnectId makes it difficult to reliably manage connections. The issue arises from the use of DateTime.UtcNow.Ticks, which can produce the the same value (I believe if called within the same 100 ns window).

I believe the following modification to using DateTime.UtcNow.Ticks would be a simple fix:
https://stackoverflow.com/questions/5608980/how-to-ensure-a-timestamp-is-always-unique/14369695
(the HiResDateTime solution provided by the answer by Ian)

```csharp
//Some c# code if needed
_connectId = DateTime.UtcNow.Ticks;
```

**Comment by RevenantX** [comment]
@Mukikaizoku hi! This is not real connectId. This is connect time used for internal logic (and it works for this perfectly). I will just rename this variable. To got real connect id for your specific purposes you can just call EndPoint.GetHashCode().

**Comment by Alloc86** [comment]
A hashcode is not really unique either though. Not even an IPv4 endpoint is an int itself (4 bytes IP + 2 bytes port -> collisions possible) it's even more so with IPv6. Of course this is mostly an academical issue as the collisions are relatively unlikely.
But wouldn't it be actually enough to just have an connection id counter that you increment by one for  each new connect? Would work without any wrapping for 2^31 connections after all :)

**Comment by wobes1** [comment]
+ for that one

**Comment by Mukikaizoku** [comment]
@RevenantX Thanks for the quick response! If it's a time stamp needed for internal logic, then certainly a name change would be good as to not mislead. Otherwise I agree with @Alloc86 with an additional thought that EndPoint.GetHashCode() could have issues with NAT possibly?

**Comment by RevenantX** [comment]
>that EndPoint.GetHashCode() could have issues with NAT possibly?

No. Why?) peers behind NAT after connection to "server" will get different ports, so peers behind NAT and any other peers in same situtation) IPEndPoint.GetHashCode() includes port.

**Comment by RevenantX** [comment]
> 
> 
> A hashcode is not really unique either though. Not even an IPv4 endpoint is an int itself (4 bytes IP + 2 bytes port -> collisions possible) it's even more so with IPv6. Of course this is mostly an academical issue as the collisions are relatively unlikely.
> But wouldn't it be actually enough to just have an connection id counter that you increment by one for each new connect? Would work without any wrapping for 2^31 connections after all :)

Why you need some id (as int or long value)? There already many helpful methods in NetManager (and foreach in 0.8.x)
```csharp
for(NetPeer peer in netServer)
{
    if(peer.ConnectionState == ConnectionState.Connected)
        //do something with peer
}
```

**Comment by wobes1** [comment]
> > A hashcode is not really unique either though. Not even an IPv4 endpoint is an int itself (4 bytes IP + 2 bytes port -> collisions possible) it's even more so with IPv6. Of course this is mostly an academical issue as the collisions are relatively unlikely.
> > But wouldn't it be actually enough to just have an connection id counter that you increment by one for each new connect? Would work without any wrapping for 2^31 connections after all :)
> 
> Why you need some id (as int or long value)? There already many helpful methods in NetManager (and foreach in 0.8.x)
> 
> ```cs
> for(NetPeer peer in netServer)
> {
>     if(peer.ConnectionState == ConnectionState.Connected)
>         //do something with peer
> }
> ```

To send a message to a specific peer by having a dictionary <long, NetPeer> on the Server. Just in case if I don't want to store reference, but just an id so I can access the dictionary later on.

**Comment by wobes1** [comment]
I am using ECS. And I don't want to use ISharedComponentData to reference a peer. Instead I am using IComponentData which supports only bittable

**Comment by xmedeko** [comment]
I am generating a simple `ClientId` as a long counter and put is as `NetPeer.Tag` on the server. I use it to tag internal data to know which client has generated them. The reason is:
- Simple eval using `!=`. The `IPEndPoint` has Equals overridden, but it's a bit slower and must resolve nulls.
- Do not need to store Weak reference or implement some other king of cleanup.

Summary: `IPEndPoint` would serve the same purpose, but is more hassle.

Note: this kind of counter id should not be shared with clients for the security reasons (cheating). If someone needs to resend some client id between client and server, then it's better to use `new Guid()`.

@RevenantX if you do not have any other reason to keep `ConnectId` as current time (like security), then making it as a simple counter so other folks may use it, too.

**Comment by SmiggsGDog** [comment]
+1 for a unique connectId. I actually assumed it was already due to this line in the documentation "Connection id for internal purposes, but can be used as key  in your dictionary of peers". 

Looking through the code it appears that is used to address clients on connect, granted I don't fully understand the code, but could this not be problematic? For example if one connection is accepted and the other is rejected.

@xmedeko I've been thinking about what you're saying about security and I don't think it should really be an issue if clients know the ID of other players. That is unless you let the client identify themselves within the packet data they are sending. Maybe I'm missing something, but your authority (server) should check that the NetPeer that sent the packet has authority to do so for the object they are trying to control, before the packet is even opened. 

@RevenantX Thanks for this amazing library.

**Comment by RevenantX** [comment]
I think i will make this ConnectID unique(maybe just counter). And i must rework some connection logic.

**Comment by wobes1** [comment]
Спасибо )
