### ISSUE TITLE
Why do Socket.Poll used ?

### ISSUE THREAD

**Issue by moien007** [RevenantX/LiteNetLib#238]
https://github.com/RevenantX/LiteNetLib/blob/7264fb0777b0fbd92fd64037bd0882c806c76d51/LiteNetLib/NetSocket.cs#L67-L69

https://github.com/RevenantX/LiteNetLib/blob/7264fb0777b0fbd92fd64037bd0882c806c76d51/LiteNetLib/NetSocket.cs#L221-L224

As you know UDP's SendTo is not a blocking call (unlike TCP's Send) and also
Socket.Poll has overhead especially on Windows,  Why not just call ReceiveFrom and SendTo ?
And even more further why not use Async Socket API ?

**Comment by RevenantX** [comment]
@moien007 
`Socket.ReceiveFrom` inside infinte loop will eat 100% cpu. 
`Socket.SendTo` will throw exception if there buffer overflow and we try sending some packets.
> And even more further why not use Async Socket API ?

There is no sense in async api because inside it uses same WINSOCK api that isn't async. There was some tries of using async api but they didn't give any performance.

**Comment by moien007** [comment]
@RevenantX 

> Socket.ReceiveFrom inside infinte loop will eat 100% cpu.
> Socket.SendTo will throw exception if there buffer overflow and we try sending some packets.

https://github.com/RevenantX/LiteNetLib/blob/7264fb0777b0fbd92fd64037bd0882c806c76d51/LiteNetLib/NetSocket.cs#L96
https://github.com/RevenantX/LiteNetLib/blob/7264fb0777b0fbd92fd64037bd0882c806c76d51/LiteNetLib/NetSocket.cs#L128

That's because your setting `Socket.Blocking` to `false`. Non-blocking sockets are poorly implemented on Windows and even on Linux non-blocking sockets are not preferred over async-io.
You can use Stopwatch and measure how badly Socket.Poll respects to timeout value that you passed.
<br>
> There is no sense in async api because inside it uses same WINSOCK api that isn't async. There was some tries of using async api but they didn't give any performance.

https://github.com/RevenantX/LiteNetLib/blob/7264fb0777b0fbd92fd64037bd0882c806c76d51/LiteNetLib/NetSocket.cs#L17-L18

With async api you don't need to create threads which wastes system resources and also I disagree with **"There was some tries of using async api but they didn't give any performance"**.

**Comment by moien007** [comment]
@RevenantX  

> Blocking UDP socket doesn't close properly on .NET Core under linux and in unity3d with IL2CPP usage

What about Async UDP socket ?

> Async api uses threadpool. There is no much difference. 

So if there is not difference between creating new thread and using threadpool, why do threadpool exist ?
By using async api, CLR will run callbacks when data received, it's clearly better than making two thread busy behind low-level socket API's which does P/Invoke every time get called.

**Comment by xmedeko** [comment]
@moien007 Threadpool exists, because creating Thread is CPU and memory (1MB mem) intensive  operation. So, if you need to run many short tasks in background, the threadpool saves you time and memory. But if you need long running tasks, then use threads.
This does not justify using threads in LiteNetLib. I do nothing about perfomance, but threadpool has a disadvantage, that wrong task may exhaust the threadpool and then you are screwed. (And it's very easy to write such wrong task, e.g. a task doing some I/O without async). So, from the robustness perspective, I vote for threads since the LiteNetLib is core functionality for me.

**Comment by moien007** [comment]
@xmedeko

>  This does not justify using threads in LiteNetLib. I do nothing about perfomance, but threadpool has a disadvantage, that wrong task may exhaust the threadpool and then you are screwed. 

Do calling `Socket.ReceiveFromAsync` is a wrong task ? Even if it is, at least we can have two receive logic, a non-blocking receive logic (**NRL**) and blocking receive logic (**BRL**).  So we can use **BRL** if operation system is Windows, else use **NRL**. BTW, we still have async api on the table.

**Comment by xmedeko** [comment]
Nope, `Socket.ReceiveFromAsync` is a good task. You may have good async code in UDP networking, but often you do other stuff on the server or app - write file, communication with DB, ... and you easily put (foget) some sync IO in a Task. Everything look well until some IO problem occurs - DB server overloaded, disk failures, ... Then you exhaust the threadpool and no async task can pass, even the UDP.

**Comment by moien007** [comment]
@xmedeko I cannot understand what do you mean, do you mean a case that exception thrown within 
async receive callback ?

**Comment by xmedeko** [comment]
It's not exactly topic of this issue. But e.g. something like:
```c#
for (int i = 0; i++; i <= 100)
   Task.Run(LongRunningMethod);
// ...
private void LongRunningMethod() => Thread.Sleep(600*1000);
```
Where instead of `Thread.Sleep` you may have e.g. stale DB query (non async) etc. Yes, it's a programming bug. But such bug in a low important part of program hangs all tasks. (Yes, it's possible to have separate thread pool, but who do it?)

I do not say is't a killer reason for Thread code. If the LiteNetLib would be async, I would use it too. I just think Threads has the slight advantage of robustness.

**Comment by RevenantX** [comment]
@moien007 i changed non blocking sockets to blocking. Latency must be reduced.
