### ISSUE TITLE
[Feature] "Long term support" branches instead of released builds

### ISSUE THREAD

**Issue by alexr1221** [RevenantX/LiteNetLib#321]
Hello!

Correct me if I am wrong but the actual system consists in fixing the bugs in the master branch (e.g. 0.9), and then merging all the fixes (concerning the old versions too) in a new stable build (e.g. 0.8.4) few weeks later?

Don't you think it would be clearer and easier to manage to fix the bugs at the same time in the master branch (e.g. 0.9) and in "long term support" branches (e.g. 0.8 [Long Term Support])?

It would also obviously bring the fixes faster for the stable versions.

I really liked this shift made by Unity concerning version management from '5.6.x and patches' to 'U.2019.x and long term support'

Regards

**Comment by RevenantX** [comment]
@alexr1221 hi. I almost always fix bugs in that way. There is no critical bugs in 0.8 (if someone need some fix he can just write to me). Critical bugs - fixed immediately. And many peoples use master version. 
0.9 branch changed in some ways (because of channels) and there is specific bug fixes and speed improvements that not always compatible with old version.

**Comment by ArnaudValensi** [comment]
@RevenantX It's been a year and two months since the last release. Do you still recommend using the last release or is it better to use master?

**Comment by RevenantX** [comment]
@ArnaudValensi now master is close to release, and faster (and with some fixes) than 0.8. So master for now is something like RC (release candidate)
