### ISSUE TITLE
Packet fragmentation, unreliable delivery method

### ISSUE THREAD

**Issue by qxxxb** [RevenantX/LiteNetLib#357]
What's the suggested method for fragmenting packets sent with `DeliveryMethod.Unreliable`?

**Library version**: 0.8.3

**Framework**: MonoGame

**OS**: Windows

**Comment by RevenantX** [comment]
@qxxxb fragment logically by hands.
For example if you have 1000 positions that have size more than MTU
you can send 500 first positions in first packet
and second 500 positions in second packet
This allows to partially receive data even if one packet lost. (in fragmented mode this will be unavailable because fragments will be split by another algorithm)
