### ISSUE TITLE
Porting to Go

### ISSUE THREAD

**Issue by maclof** [RevenantX/LiteNetLib#379]
Hey, no issue here, I just wanted to let you know @RevenantX that I am currently porting your package to Go

My work can be found here:
https://github.com/maclof/litenetlib-go

Excellent library by the way :)

**Comment by RevenantX** [comment]
Strange idea, because in most cases Reliable UDP used for dedicated servers that share logic with client, so servers for C# games (on unity,monogame,godot) will use same technology or at least same language (.net core is actually very good). So there isn't much sense to write client code twice in different languages. Also it will be a bit hard to stay in sync with fresh updates and improvements. But if you want - why not :)

**Comment by maclof** [comment]
@RevenantX I understand and that is how I intend to use your library, however this is intended for a larger infrastructure setup, client connects to a golang udp litenetlib cluster, logs in, joins lobby etc, queues to join a game. The golang cluster then spawns a new game server once required players are met (a Unity C# coded server) then the clients seamlessly connect to the unity litenetlib server.

**Comment by maclof** [comment]
@RevenantX also I have use cases for both libraries outside of game development, simple reliable UDP messaging between services.

**Comment by RevenantX** [comment]
@maclof i think in most cases for "logs in", "lobbies", "messaging between services" better use plain TCP socket, or some lightweight library. It more reliable and faster for this. This is not hard to add simple "packet" handler in TCP.
