### ISSUE TITLE
Suggestion: Distribute via open upm & unity package manager

### ISSUE THREAD

**Issue by kkjamie** [RevenantX/LiteNetLib#445]
Have you considered distributing unity releases via https://openupm.com?

This way it's much easier to maintain inside unity projects via the package manager. It's minimal effort I believe, I think they have a CI for automated releases from github, so once it's setup it should be able to detect new releases automatically
I think the directory structure may need to be tweaked though. I realise it's not just a unity library of course.

**Comment by JerryLiew** [comment]
i think its a good idea.but as the README.md shown, "Always use library sources instead of precompiled DLL files ( because there are platform specific #ifdefs and workarounds for unity bugs )" ,it may cause some problems.(Of course, i dont know about the details,maybe it can works well)

**Comment by aaronchapin-tocaboca** [comment]
It's also possible to distribute via the UPM via git now. I've opened a PR to enable that.

**Comment by RevenantX** [comment]
you can now add to manifset.json `"com.revenantx.litenetlib": "https://github.com/RevenantX/LiteNetLib.git?path=/LiteNetLib#upm"`

**Comment by robinnorth** [comment]
FYI I have added the package available on the UPM branch to OpenUPM: https://openupm.com/packages/com.revenantx.litenetlib/

The only issue is that there is a discrepancy between the UPM package version (shown as `v1.0.1-1`) and the library version (`v.1.1.0`), as the version number in `package.json` was not bumped until after the `v1.1.0` tag which OpenUPM uses to build the UPM package version. To avoid this going forward, `package.json` simply needs to have its version number updated in line with the library so that when future release Git tags are created, the UPM and library versions are in sync.

Cheers!

**Comment by robinnorth** [comment]
Actually, as it turns out, OpenUPM support isn't quite so straightforward. As the Unity `.meta` files only exist in the UPM branch, they don't get included in the package build OpenUPM produces, as the Git tags it uses to detect versions to build are on `master`.

A solution would be to tag releases on the UPM branch with a special prefix, e.g. `upm-v1.1.0` to enable OpenUPM to be configured to only build releases from those tags : 
![image](https://github.com/RevenantX/LiteNetLib/assets/3787255/00bd437b-0347-4bfa-a4df-3e968bdbb9f9)

**Comment by RevenantX** [comment]
https://openupm.com/packages/com.revenantx.litenetlib/?subPage=readme
