### ISSUE TITLE
Crash when client sends some random message

### ISSUE THREAD

**Issue by QPRocky** [RevenantX/LiteNetLib#53]
If client sends some random message and server havent following:
netSerializer.SubscribeReusable<RandomMessage, NetPeer>(OnRandomMessage);
server will crash.
Or is there something I have missed?

**Comment by QPRocky** [comment]
Also if client message differs what server is excepting, server will crash.

Client sends:
public class SomeMessage
{
    public int SomeInt { get; set; }
    public string MaliciousExtraString { get; set; }
}

Server is excepting
public class SomeMessage
{
    public int SomeInt { get; set; }
}

**Comment by timematcher** [comment]
I have observed intermittent server crash as well in some of my testing with multiple clients (on different tiers) when random or corrupted message is sent to the server. Maybe we should implement some way to handle it in the library , define some kind of protocol and if the packet is not per as protocol, the packet is discarded.

**Comment by RevenantX** [comment]
@QPRocky yes this is by design right now. I can add ```try { ... } catch { ... }``` to read method and return some bool (true if all ok - false otherwise). Or you can add ```try { ... } catch { ... }``` in your code.

**Comment by marsermd** [comment]
I don't use NetSerializer class because we have our in-house code generator for various purposes, including serialization.
But if I used it, I would prefer to handle some ParseException containing details of what went wrong. This is useful for debug purposes.

### Why validating messages?
It is absolutely a must-have for any networking solution where sever accepts packets. If messages are not validated, malicious packets can be sent to server(examples of such packets greatly depends on the app)

### How to validate messages?
The way we approach handling corrupted messages is following:
Each field can have a set of attributes that define behaviour of validation stage. 
Examples: 
```
[MinimumCollectionLength(1)]
[MaximumCollectionLength(10)]
int[] LevelIds;

[NotNull]
Planet Earth;

[MagnitudeLessThen(1)]
Vector3 speed;
```
Then we generate code that checks all necessary conditions. You could add those checks to RegisterInternal function.

**Comment by RevenantX** [comment]
@marsermd serializer will be rewritted a little. But this solution is specially simple. For users who need powerfull (and slow) serialization - they can use some third party cool library for that.
My serializator for simple games and fast prototyping.

**Comment by marsermd** [comment]
That's a fair answer.
P.s. powerful serialization is not necessary slow. If based on code generation, it can be very efficient:) But that's definetly not what you'd like to include in your project:)

**Comment by RevenantX** [comment]
>P.s. powerful serialization is not necessary slow. 

I agree. There is popular well tested **Protobuf** and **Flatbuffers** that very good at speed.

**Comment by marsermd** [comment]
Returning to the original question. And related to #89 
Probably the best _design_ is to add a 
```
try { ... } 
catch (Exception e)
{
    throw new BadMessageException(ex.Message, ex);
}
```
And document that it is possible in a real world documentation.

This technique would allow to throw more specific erors in future(if needed), it works currently and gives user a hint of what's going on.

**Comment by GutterLab** [comment]
I thought the solution to this was to check the length of the remaining bytes, if it's not what's expected drop the packet.
