### ISSUE TITLE
Message sended/received twice with IPv6Enabled

### ISSUE THREAD

**Issue by michael-balle** [RevenantX/LiteNetLib#533]
Hi,
I have IPv6Enabled and when I send a message from the client to server (two Unity applications on the same machine) I get them twice on the server – one via IPv4 and the same via IPv6.

Thought the NetManager checks if IPv6 works and then only sends the message once via IPv6 (if not sends it automatically via IPv4 only).

How can I fix this (except by disabling IPv6)?

**Comment by RevenantX** [comment]
@michael-balle hi. Can you send minimal example project with reproduce?

**Comment by michael-balle** [comment]
[SvNetworkManagerClient.txt](https://github.com/RevenantX/LiteNetLib/files/12835650/SvNetworkManagerClient.txt)
[SvNetworkManagerServer.txt](https://github.com/RevenantX/LiteNetLib/files/12835652/SvNetworkManagerServer.txt)
[SvNetworkMessageTypes.txt](https://github.com/RevenantX/LiteNetLib/files/12835653/SvNetworkMessageTypes.txt)

**Comment by RevenantX** [comment]
@michael-balle seems that it's because you broadcasting and received both ipv4 and ipv6 address. 
![image](https://github.com/RevenantX/LiteNetLib/assets/825465/36cbd5b9-dbca-4a4b-880b-e2bba1e54da8)
Check on connected client will not save here, because connecting taking some time. You can use GetPeersCount(ConnectionState.Any)

**Comment by michael-balle** [comment]
Great, thank you.
