### ISSUE TITLE
Connect to server without key requirement

### ISSUE THREAD

**Issue by iltan987** [RevenantX/LiteNetLib#571]
1- Right now, using a key is a must for connecting to the server from a client. I think it should be optional.

2- Also, another thing. For the connection part, only string is accepted. It should accept primitive types, or custom serializable types as well. AcceptIfKey(string) is the function I am talking about

**Comment by RevenantX** [comment]
@iltan987 
1. this is by design to protect from accidental connection from another LiteNetLib based project/game/
2. There is Connect with NetDataWriter argument where you can put anything including byte array. That you can later read in OnConnectionRequest inside request.

https://revenantx.github.io/LiteNetLib/api/LiteNetLib.NetManager.html#LiteNetLib_NetManager_Connect_System_Net_IPEndPoint_LiteNetLib_Utils_NetDataWriter_
